name: Run preparations before updating

on:
  workflow_call:
    outputs:
      cache-key:
        description: The key name of the files that were saved to the cache.
        value: ${{ steps.save-cache.inputs.key }}

jobs:
  pre-update:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Merge updates from 'main'
        run: git fetch origin live:live && git checkout live -- docs/ics
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install