name: Automatic update

on:
  schedule:
    - cron: "0 * * * *" # Every hour
  push:
    branches: ["main"]

concurrency:
  group: "update-calendar"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Prepare update
        id: prepare
        uses: ./.github/workflows/pre-update
      - name: Update FIH calendar
        if: ${{ steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success' }}
        run: npm run fetch fih
      - name: Update EHL calendar
        if: ${{ steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success' }}
        run: npm run fetch ehl
      - name: Update KNHB calendar
        if: ${{ steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success' }}
        run: npm run fetch knhb
      - name: Finalize update
        if: ${{ steps.checkout.outcome == 'success' && steps.prepare.outcome == 'success' }}
        uses: ./.github/workflows/post-update