name: Manual update

on:
  workflow_dispatch:
    inputs:
      fetcher:
        description: "The calendar to update."
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - fih
          - ehl
          - knhb

concurrency:
  group: "update-calendar"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'latest'
      - name: Prepare update
        uses: ./.github/workflows/pre-update
      - name: Update the calendar (${{ inputs.fetcher || 'all' }})
        run: npm run fetch ${{ inputs.fetcher || 'all' }}
      - name: Finalize update
        uses: ./.github/workflows/post-update