name: Update and publish all calendars

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
#  schedule:
#    - cron: "0 * * * *"

concurrency:
  group: "update-calendar"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Prepare update
        uses: ./.github/workflows/pre-update
      - name: Update all calendars
        run: npm run fetch-all
      - name: Finalize update
        uses: ./.github/workflows/post-update