name: Update the website

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pre-fetch:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Setup pages
        uses: actions/configure-pages@v5


  fetch-fih:
    runs-on: ubuntu-latest
    needs: pre-fetch
    permissions:
      contents: write

    steps:
      - name: Fetch FIH matches
        run: npm start fih

  fetch-knhb:
    runs-on: ubuntu-latest
    needs: pre-fetch
    permissions:
      contents: write

    steps:
      - name: Fetch KNHB matches
        run: npm start knhb

  publish:
    runs-on: ubuntu-latest
    needs:
      - fetch-knhb
      - fetch-fih
      
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
