name: Update and publish the calendar

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 * * * *"
#  push:
#    branches:
#      - "main"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Prepare update
        uses: ./.github/workflows/pre-update.yml
      - name: Fetch FIH matches
        run: npm run fetch fih
      - name: Fetch EHL matches
        run: npm run fetch ehl
      - name: Fetch KNHB matches
        run: npm run fetch knhb
      - name: Finalize update
        uses: ./.github/workflows/post-update.yml