name: Update the website

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Fetch FIH matches
        run: npm run fetch fih
      - name: Fetch KNHB matches
        run: npm run fetch knhb
      - name: Save fetchers
        run: npm run save-fetchers
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
